# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.__version__

'1.22.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
print(a)
print(a.size)
print(a.shape)

[[[0.62036891 0.09521503 0.70600057 0.50591409 0.26114361]
  [0.09136948 0.97335713 0.33201413 0.36444667 0.8560176 ]
  [0.60171859 0.34275814 0.64653508 0.67561578 0.67341981]]

 [[0.85353903 0.43808048 0.4862616  0.19828811 0.01913432]
  [0.98777151 0.6825457  0.22964853 0.20045977 0.11989015]
  [0.54256209 0.12272927 0.06281364 0.65763035 0.24875972]]]
30
(2, 3, 5)


In [4]:
# Method 2
a = np.random.randint(10, size=(2,3,5))
print(a)
print(a.size)
print(a.shape)

[[[5 2 0 6 6]
  [3 1 6 0 8]
  [7 4 1 4 7]]

 [[1 9 5 1 5]
  [2 1 1 6 4]
  [3 0 7 1 0]]]
30
(2, 3, 5)


In [5]:
# Method 3
a = np.random.rand(2,3,5)
print(a)
print(a.size)
print(a.shape)

[[[0.35675082 0.85015597 0.44823514 0.42115379 0.45269051]
  [0.65087339 0.53990176 0.84512312 0.71493803 0.40982498]
  [0.42268766 0.33752523 0.8949919  0.92556819 0.98581824]]

 [[0.64078551 0.74559861 0.34670407 0.11233702 0.0088953 ]
  [0.02113314 0.95868713 0.61661938 0.00396957 0.90632036]
  [0.57902052 0.98761541 0.87828359 0.91382006 0.06677903]]]
30
(2, 3, 5)


In [6]:
# Using for loop
a_lst = [[[np.random.randint(5) for i in range(5)] for j in range(3)] for k in range(2)]
a1 = np.array(a_lst)
print(a1)
print(a1.size)
print(a1.shape)

[[[1 3 2 2 4]
  [3 0 0 0 1]
  [4 0 1 0 4]]

 [[0 4 1 3 2]
  [4 0 0 0 2]
  [4 1 3 3 3]]]
30
(2, 3, 5)


#### 4. Print *a*.


In [7]:
# your code here
print(a)

[[[0.35675082 0.85015597 0.44823514 0.42115379 0.45269051]
  [0.65087339 0.53990176 0.84512312 0.71493803 0.40982498]
  [0.42268766 0.33752523 0.8949919  0.92556819 0.98581824]]

 [[0.64078551 0.74559861 0.34670407 0.11233702 0.0088953 ]
  [0.02113314 0.95868713 0.61661938 0.00396957 0.90632036]
  [0.57902052 0.98761541 0.87828359 0.91382006 0.06677903]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [9]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
print(f'size of a: {a.size} - size of b: {b.size}')
print(f'shape of a: {a.shape} - shape of b: {b.shape}')

if a.size == b.size:
    print("a and b have same size")
else:
    print("a and b haven't same size")

size of a: 30 - size of b: 30
shape of a: (2, 3, 5) - shape of b: (5, 2, 3)
a and b have same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here
print("Because they aren't same shape")
np.add(a, b)

Because they aren't same shape


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here
c = np.resize(b, (2, 3, 5))
print(c.shape)
print(c)

(2, 3, 5)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here
print("Because they are same shape")
d = np.add(a, c)
print(d.shape)
print(d)

Because they are same shape
(2, 3, 5)
[[[1.35675082 1.85015597 1.44823514 1.42115379 1.45269051]
  [1.65087339 1.53990176 1.84512312 1.71493803 1.40982498]
  [1.42268766 1.33752523 1.8949919  1.92556819 1.98581824]]

 [[1.64078551 1.74559861 1.34670407 1.11233702 1.0088953 ]
  [1.02113314 1.95868713 1.61661938 1.00396957 1.90632036]
  [1.57902052 1.98761541 1.87828359 1.91382006 1.06677903]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [17]:
# your code/answer here
print(a)
print(d)
print('Values of array d are values of array a added to values of array c (always value 1), wich is other shape of array b')

[[[0.35675082 0.85015597 0.44823514 0.42115379 0.45269051]
  [0.65087339 0.53990176 0.84512312 0.71493803 0.40982498]
  [0.42268766 0.33752523 0.8949919  0.92556819 0.98581824]]

 [[0.64078551 0.74559861 0.34670407 0.11233702 0.0088953 ]
  [0.02113314 0.95868713 0.61661938 0.00396957 0.90632036]
  [0.57902052 0.98761541 0.87828359 0.91382006 0.06677903]]]
[[[1.35675082 1.85015597 1.44823514 1.42115379 1.45269051]
  [1.65087339 1.53990176 1.84512312 1.71493803 1.40982498]
  [1.42268766 1.33752523 1.8949919  1.92556819 1.98581824]]

 [[1.64078551 1.74559861 1.34670407 1.11233702 1.0088953 ]
  [1.02113314 1.95868713 1.61661938 1.00396957 1.90632036]
  [1.57902052 1.98761541 1.87828359 1.91382006 1.06677903]]]
Values of array d are values of array a added to values of array c (always value 1), wich is other shape of array b


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [18]:
# your code here
e = np.multiply(a, c)
print(a)
print(c)
print(e)

[[[0.35675082 0.85015597 0.44823514 0.42115379 0.45269051]
  [0.65087339 0.53990176 0.84512312 0.71493803 0.40982498]
  [0.42268766 0.33752523 0.8949919  0.92556819 0.98581824]]

 [[0.64078551 0.74559861 0.34670407 0.11233702 0.0088953 ]
  [0.02113314 0.95868713 0.61661938 0.00396957 0.90632036]
  [0.57902052 0.98761541 0.87828359 0.91382006 0.06677903]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[0.35675082 0.85015597 0.44823514 0.42115379 0.45269051]
  [0.65087339 0.53990176 0.84512312 0.71493803 0.40982498]
  [0.42268766 0.33752523 0.8949919  0.92556819 0.98581824]]

 [[0.64078551 0.74559861 0.34670407 0.11233702 0.0088953 ]
  [0.02113314 0.95868713 0.61661938 0.00396957 0.90632036]
  [0.57902052 0.98761541 0.87828359 0.91382006 0.06677903]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [19]:
# your code/answer here
if (a == e).all():
    print("a and e have same values because values of c are 1 and any number multiplied by 1 is that same number")
else:
    print("a and e haven't same values")

a and e have same values because values of c are 1 and any number multiplied by 1 is that same number


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [20]:
# your code here
print(d)
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
print(f'd_max is {d_max}')
print(f'd_min is {d_min}')
print(f'd_mean is {d_mean}')

[[[1.35675082 1.85015597 1.44823514 1.42115379 1.45269051]
  [1.65087339 1.53990176 1.84512312 1.71493803 1.40982498]
  [1.42268766 1.33752523 1.8949919  1.92556819 1.98581824]]

 [[1.64078551 1.74559861 1.34670407 1.11233702 1.0088953 ]
  [1.02113314 1.95868713 1.61661938 1.00396957 1.90632036]
  [1.57902052 1.98761541 1.87828359 1.91382006 1.06677903]]]
d_max is 1.987615412575962
d_min is 1.0039695736398273
d_mean is 1.5680935810748124


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [21]:
# your code here
f = np.empty((2, 3, 5))
print(f)

[[[1.35675082 1.85015597 1.44823514 1.42115379 1.45269051]
  [1.65087339 1.53990176 1.84512312 1.71493803 1.40982498]
  [1.42268766 1.33752523 1.8949919  1.92556819 1.98581824]]

 [[1.64078551 1.74559861 1.34670407 1.11233702 1.0088953 ]
  [1.02113314 1.95868713 1.61661938 1.00396957 1.90632036]
  [1.57902052 1.98761541 1.87828359 1.91382006 1.06677903]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [22]:
# your code here
for i in d:
    for j in i:
        for k in j:
            if k > d_min and k < d_mean:
                f[np.where(f == k)] = 25
            elif k > d_mean and k < d_max:
                f[np.where(f == k)] = 75
            elif k == d_mean:
                f[np.where(f == k)] = 50
            elif k == d_min:
                f[np.where(f == k)] = 0
            elif k == d_max:
                f[np.where(f == k)] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [23]:
# your code here
print(d)
print(f)

[[[1.35675082 1.85015597 1.44823514 1.42115379 1.45269051]
  [1.65087339 1.53990176 1.84512312 1.71493803 1.40982498]
  [1.42268766 1.33752523 1.8949919  1.92556819 1.98581824]]

 [[1.64078551 1.74559861 1.34670407 1.11233702 1.0088953 ]
  [1.02113314 1.95868713 1.61661938 1.00396957 1.90632036]
  [1.57902052 1.98761541 1.87828359 1.91382006 1.06677903]]]
[[[ 25.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 25.  25.  75.  75.  75.]]

 [[ 75.  75.  25.  25.  25.]
  [ 25.  75.  75.   0.  75.]
  [ 75. 100.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [24]:
# your code here
print(d)
g = np.empty(d.shape, dtype='str')
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i, j])):
            if d[i, j ,k] > d_min and d[i, j ,k] < d_mean:
                g[i, j ,k] = 'B'
            elif d[i, j ,k] > d_mean and d[i, j ,k] < d_max:
                g[i, j ,k] = 'D'
            elif d[i, j ,k] == d_mean:
                g[i, j ,k] = 'C'
            elif d[i, j ,k] == d_min:
                g[i, j ,k] = 'A'
            elif d[i, j ,k] == d_max:
                g[i, j ,k] = 'E'

print(g)

[[[1.35675082 1.85015597 1.44823514 1.42115379 1.45269051]
  [1.65087339 1.53990176 1.84512312 1.71493803 1.40982498]
  [1.42268766 1.33752523 1.8949919  1.92556819 1.98581824]]

 [[1.64078551 1.74559861 1.34670407 1.11233702 1.0088953 ]
  [1.02113314 1.95868713 1.61661938 1.00396957 1.90632036]
  [1.57902052 1.98761541 1.87828359 1.91382006 1.06677903]]]
[[['B' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'B']
  ['B' 'B' 'D' 'D' 'D']]

 [['D' 'D' 'B' 'B' 'B']
  ['B' 'D' 'D' 'A' 'D']
  ['D' 'E' 'D' 'D' 'B']]]
